### ISSUE TITLE
Missing part of MAKEME

### ISSUE THREAD

**Issue by eidosam** [SarKurd/hyf-javascript2#4]
Quoting from [HackYourFuture/JavaScript - Week4/MAKEME.md](https://github.com/HackYourFuture/JavaScript/blob/master/Week4/MAKEME.md#step-3-custom-dom-manipulation-challenge-mortar_board) 
> Make an object containing information for each book. Each item (object) in this object should have the book ID you thought up in point 1 as a key, and it should have at least the following fields: title, language and author.

This part is not addressed, instead these information are created programmatically, like 
https://github.com/SarKurd/hyf-javascript2/blob/2c283d7089b7943009dae3e85e5199b1233ed86d/week1/script.js#L46-L53

**Comment by SarKurd** [comment]
I created titles programmatically, i don't know if this counts as an issue, i though it's a better idea to programmatically generate the titles.

**Comment by eidosam** [comment]
I totally agree with you on
> i though it's a better idea to programmatically generate the titles.

In case of the information are not existing, or costly to obtain. 

This issue is specially about the requirements in the HW.

**Comment by SarKurd** [comment]
I'll try to follow the requirements in the HWs next time

Thanks for your feedback .
